# Generated by Django 2.2.28 on 2025-11-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('pedi_empr', models.IntegerField()),
                ('pedi_fili', models.IntegerField()),
                ('pedi_nume', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('pedi_data', models.DateField()),
                ('pedi_tota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pedi_canc', models.BooleanField(default=False)),
                ('pedi_fina', models.CharField(choices=[('0', 'À VISTA'), ('1', 'A PRAZO'), ('2', 'SEM FINANCEIRO')], default='0', max_length=100)),
                ('contato_realizado', models.BooleanField(default=False)),
                ('data_contato', models.DateField(blank=True, null=True)),
                ('notas_contato', models.TextField(blank=True, null=True)),
                ('pedi_stat', models.CharField(choices=[('Pendente', 'Pendente'), ('Processando', 'Processando'), ('Enviado', 'Enviado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50)),
                ('pedi_obse', models.TextField(blank=True, null=True)),
                ('pedi_forn', models.ForeignKey(db_column='pedi_forn', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_por_clientes', to='Entidades.Entidades')),
                ('pedi_vend', models.ForeignKey(db_column='pedi_vend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_vendedor', to='Entidades.Entidades')),
            ],
            options={
                'db_table': 'pedidosvenda',
            },
        ),
        migrations.CreateModel(
            name='Itenspedidovenda',
            fields=[
                ('iped_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('iped_fili', models.IntegerField(unique=True)),
                ('iped_item', models.IntegerField()),
                ('iped_quan', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('iped_unit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('iped_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iped_fret', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iped_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iped_unli', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('iped_forn', models.IntegerField(blank=True, null=True)),
                ('iped_vend', models.IntegerField(blank=True, null=True)),
                ('iped_cust', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('iped_tipo', models.IntegerField(blank=True, null=True)),
                ('iped_desc_item', models.BooleanField(blank=True, null=True)),
                ('iped_perc_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iped_unme', models.CharField(blank=True, max_length=6, null=True)),
                ('iped_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='Pedidos.PedidoVenda')),
            ],
            options={
                'db_table': 'itenspedidovenda',
            },
        ),
    ]
