# Generated by Django 2.2.28 on 2025-11-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedidovenda',
            name='iped_prod',
            field=models.ForeignKey(db_column='prod_codi', on_delete=django.db.models.deletion.CASCADE, to='produto.Produtos'),
        ),
        migrations.AlterUniqueTogether(
            name='itenspedidovenda',
            unique_together={('iped_empr', 'iped_fili', 'iped_pedi', 'iped_item')},
        ),
    ]
