# Generated by Django 5.1.1 on 2024-10-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldoproduto',
            name='produto_codigo',
        ),
        migrations.AddField(
            model_name='saldoproduto',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.produtos'),
            preserve_default=False,
        ),
    ]
