# Generated by Django 5.1.5 on 2025-02-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='produto_codigo',
            new_name='prod_codi',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='codigo_fabricante',
            new_name='prod_codi_fabr',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='familia',
            new_name='prod_fami',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='foto',
            new_name='prod_foto',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='grupo',
            new_name='prod_grup',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='local',
            new_name='prod_loca',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='marca',
            new_name='prod_marc',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='ncm',
            new_name='prod_ncm',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='nome_produto',
            new_name='prod_nome',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='subgrupo',
            new_name='prod_sugr',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='unidade_medida',
            new_name='prod_unme',
        ),
        migrations.RenameField(
            model_name='saldoproduto',
            old_name='produto_codigo',
            new_name='prod_codi',
        ),
    ]
