# Generated by Django 5.1.5 on 2025-02-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_produto_codigo_produtos_prod_codi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoproduto',
            name='sapr_prod',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
