# Generated by Django 5.1.1 on 2024-10-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_saldoproduto_produto_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoproduto',
            old_name='produto',
            new_name='produto_codigo',
        ),
    ]
