# Generated by Django 5.1.5 on 2025-02-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0009_rename_usua_bloq_usuarios_ativo_and_more'),
        ('produto', '0003_saldoproduto_sapr_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldoproduto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='saldoproduto',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='saldoproduto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='saldoproduto',
            name='prod_codi',
        ),
        migrations.RemoveField(
            model_name='saldoproduto',
            name='saldo_estoque',
        ),
        migrations.AddField(
            model_name='saldoproduto',
            name='sapr_empr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='licencas.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saldoproduto',
            name='sapr_fili',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licencas.filiais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saldoproduto',
            name='sapr_sald',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saldoproduto',
            name='sapr_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produtos'),
        ),
    ]
