# Generated by Django 5.1.5 on 2025-02-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_saldoproduto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoproduto',
            name='sapr_prod',
            field=models.ForeignKey(db_column='sapr_prod', on_delete=django.db.models.deletion.CASCADE, to='produto.produtos'),
        ),
    ]
