# Generated by Django 5.1.1 on 2025-02-23 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entidades', '0001_initial'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('entr_sequ', models.IntegerField()),
                ('entr_empr', models.CharField(max_length=100)),
                ('entr_fili', models.CharField(max_length=100)),
                ('entr_prod', models.ForeignKey(db_column='entr_prod', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='entradas_produtos', serialize=False, to='produto.produtos')),
                ('entr_data', models.DateField()),
                ('entr_quan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entr_tota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entr_obse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('entr_enti', models.ForeignKey(db_column='entr_enti', on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='Entidades.entidades')),
                ('entr_usua', models.ForeignKey(db_column='entr_usua', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada Estoque',
                'verbose_name_plural': 'Entradas Estoque',
                'db_table': 'entradasestoque',
                'ordering': ['entr_sequ'],
                'unique_together': {('entr_empr', 'entr_fili', 'entr_prod', 'entr_data')},
            },
        ),
    ]
