# Generated by Django 5.1.1 on 2025-01-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas_Produtos', '0002_rename_produto_entrada_produtos_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_produtos',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data Entrada'),
        ),
    ]
