# Generated by Django 2.2.28 on 2025-11-04 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entidades', '0001_initial'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidasEstoque',
            fields=[
                ('said_sequ', models.IntegerField()),
                ('said_empr', models.CharField(max_length=100)),
                ('said_fili', models.CharField(max_length=100)),
                ('said_prod', models.ForeignKey(db_column='said_prod', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='saidas_produtos', serialize=False, to='produto.Produtos')),
                ('said_data', models.DateField()),
                ('said_quan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('said_tota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('said_obse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('said_enti', models.ForeignKey(db_column='said_enti', on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='Entidades.Entidades')),
                ('said_usua', models.ForeignKey(db_column='said_usua', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saída Estoque',
                'verbose_name_plural': 'Saídas Estoque',
                'db_table': 'saidasestoque',
                'ordering': ['-said_data'],
            },
        ),
        migrations.AddConstraint(
            model_name='saidasestoque',
            constraint=models.UniqueConstraint(fields=('said_empr', 'said_fili', 'said_prod', 'said_data'), name='pk_saida_estoque'),
        ),
    ]
