# Generated by Django 5.1.1 on 2024-10-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entidades', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida_Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidade', models.IntegerField()),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Documento')),
                ('observacoes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='Entidades.entidades')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='produto.produtos')),
            ],
            options={
                'verbose_name': 'Saída Produto',
                'verbose_name_plural': 'Saída Produtos',
            },
        ),
    ]
