# Generated by Django 5.1.1 on 2024-10-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saidas_Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saida_produtos',
            old_name='produto',
            new_name='produto_codigo',
        ),
    ]
