# Generated by Django 5.1.1 on 2025-01-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidades',
            name='enti_fant',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entidades',
            name='enti_nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
