# Generated by Django 5.1.1 on 2025-02-04 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empr_nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Licencas',
            fields=[
                ('lice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('lice_docu', models.CharField(blank=True, max_length=60, null=True, verbose_name='Documento')),
                ('lice_nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Empresa')),
                ('lice_emai', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('lice_bloq', models.BooleanField(default=False, verbose_name='Ativa?')),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
            ],
            options={
                'db_table': 'licencas',
            },
        ),
        migrations.CreateModel(
            name='Filiais',
            fields=[
                ('fili_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fili_nome', models.CharField(max_length=100, verbose_name='Nome da Filial')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='licencas.empresas')),
            ],
            options={
                'db_table': 'filiais',
            },
        ),
        migrations.AddField(
            model_name='empresas',
            name='licenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='licencas.licencas'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usua_codi', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('usua_nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('usua_login', models.CharField(blank=True, max_length=30, null=True, verbose_name='Login')),
                ('usua_data_nasc', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('usua_sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('usua_emai', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('usua_fone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('usua_senh', models.CharField(max_length=128, verbose_name='Senha')),
                ('usua_bloq', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('usua_libe_clie_bloq', models.BooleanField(default=False, verbose_name='Liberação Cliente Bloqueado')),
                ('usua_libe_pedi_comp', models.BooleanField(default=False, verbose_name='Liberação Pedido Comprado')),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('licenca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='licencas.licencas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
