# Generated by Django 5.1.1 on 2025-02-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='empr_id',
            new_name='empr_codi',
        ),
    ]
