# Generated by Django 5.1.5 on 2025-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='empr_bair',
            field=models.CharField(default='centro', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_cep',
            field=models.CharField(default=84015265, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_cida',
            field=models.CharField(default='PR', max_length=100, verbose_name='cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_docu',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_emai',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_ende',
            field=models.CharField(default='centro', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_esta',
            field=models.CharField(default='PR', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_ie',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_nume',
            field=models.CharField(default=1, max_length=10, verbose_name='Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='empr_regi',
            field=models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('regime_normal', 'Regime Normal')], default='simples_nacional', max_length=50, verbose_name='Regime Tributação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_bair',
            field=models.CharField(default='centro', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_cep',
            field=models.CharField(default=84015265, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_cida',
            field=models.CharField(default='Paraná', max_length=100, verbose_name='cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_docu',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_emai',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_ende',
            field=models.CharField(default='centro', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_esta',
            field=models.CharField(default='PR', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_ie',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_nume',
            field=models.CharField(default=1, max_length=10, verbose_name='Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiais',
            name='fili_regi',
            field=models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('regime_normal', 'Regime Normal')], default='simples_nacional', max_length=50, verbose_name='Regime Tributação'),
            preserve_default=False,
        ),
    ]
