# Generated by Django 5.1.1 on 2025-02-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencas',
            name='db_config',
            field=models.JSONField(default='default', verbose_name='Configuração do Banco de Dados'),
            preserve_default=False,
        ),
    ]
