# Generated by Django 5.1.5 on 2025-02-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0002_empresas_empr_bair_empresas_empr_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencas',
            name='lice_data_cria',
            field=models.DateField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='licencas',
            name='lice_bloq',
            field=models.BooleanField(default=False, verbose_name='Ativa?   '),
        ),
    ]
