# Generated by Django 5.1.5 on 2025-02-05 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('licencas', '0003_licencas_lice_data_cria_alter_licencas_lice_bloq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='field_log_data',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='field_log_time',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usua_senh',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_empresa', to='licencas.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_filial', to='licencas.filiais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=261270, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='licencas',
            name='lice_data_cria',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='licenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_licenca', to='licencas.licencas'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usua_data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usua_emai',
            field=models.EmailField(default=1, max_length=100, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usua_login',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usua_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
