# Generated by Django 5.1.5 on 2025-02-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0004_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencas',
            name='field_log_data',
        ),
        migrations.RemoveField(
            model_name='licencas',
            name='field_log_time',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='filial',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresas',
            field=models.ManyToManyField(related_name='usuarios_empresa', to='licencas.empresas'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='filiais',
            field=models.ManyToManyField(related_name='usuarios_filial', to='licencas.filiais'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_cida',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_docu',
            field=models.CharField(default='00000000000000', max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_nume',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='licenca',
            field=models.ForeignKey(db_column='lice_id', default='1', on_delete=django.db.models.deletion.CASCADE, to='licencas.licencas'),
        ),
        migrations.AlterField(
            model_name='filiais',
            name='fili_cida',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='filiais',
            name='fili_docu',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='filiais',
            name='fili_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filiais',
            name='fili_nume',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='licenca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_licenca', to='licencas.licencas'),
        ),
        migrations.AlterUniqueTogether(
            name='empresas',
            unique_together={('licenca', 'empr_docu')},
        ),
        migrations.AlterUniqueTogether(
            name='filiais',
            unique_together={('empresa', 'fili_docu')},
        ),
    ]
