# Generated by Django 5.1.1 on 2025-02-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0005_remove_licencas_field_log_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencas',
            options={'verbose_name': 'licencas'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
