# Generated by Django 5.1.1 on 2025-02-06 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0006_alter_licencas_options_usuarios_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='usua_libe_clie_bloq',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usua_libe_pedi_comp',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='licenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_licenca', to='licencas.licencas'),
        ),
    ]
