# Generated by Django 5.1.1 on 2025-02-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0007_remove_usuarios_usua_libe_clie_bloq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencas',
            options={'verbose_name': 'Licença'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterField(
            model_name='empresas',
            name='empr_docu',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='licenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='licencas.licencas'),
        ),
        migrations.AlterField(
            model_name='licencas',
            name='lice_bloq',
            field=models.BooleanField(default=False, verbose_name='Ativa?'),
        ),
        migrations.AlterField(
            model_name='licencas',
            name='lice_docu',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='empresas',
            field=models.ManyToManyField(related_name='usuarios', to='licencas.empresas'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='filiais',
            field=models.ManyToManyField(related_name='usuarios', to='licencas.filiais'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='licenca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='licencas.licencas'),
            preserve_default=False,
        ),
    ]
