# Generated by Django 5.1.1 on 2025-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0008_alter_licencas_options_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_bloq',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_data_nasc',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_codi',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_sexo',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usua_fone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usua_nome',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default='Leo', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
