# Generated by Django 5.1.1 on 2025-01-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('orca_id', models.AutoField(primary_key=True, serialize=False)),
                ('orca_empr', models.IntegerField()),
                ('orca_fili', models.IntegerField()),
                ('orca_codi', models.IntegerField()),
                ('orca_aber', models.DateField(blank=True, null=True)),
                ('orca_enti', models.IntegerField(blank=True, null=True)),
                ('orca_vend', models.IntegerField(blank=True, null=True)),
                ('orca_cond', models.IntegerField(blank=True, null=True)),
                ('orca_resp', models.IntegerField(blank=True, null=True)),
                ('orca_tipo_fret', models.IntegerField(blank=True, null=True)),
                ('orca_vali', models.CharField(blank=True, max_length=200, null=True)),
                ('orca_tipo_impo', models.CharField(blank=True, max_length=200, null=True)),
                ('orca_praz_entr', models.CharField(blank=True, max_length=200, null=True)),
                ('orca_obse', models.TextField(blank=True, null=True)),
                ('orca_valo_fret', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('orca_valo_outr', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('orca_valo_desc', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('orca_valo_tota', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('orca_orde_refe', models.IntegerField(blank=True, null=True)),
                ('orca_gara', models.CharField(blank=True, max_length=200, null=True)),
                ('orca_data_alte', models.DateField(blank=True, null=True)),
                ('orca_stat', models.BooleanField(blank=True, null=True)),
                ('orca_soli', models.CharField(blank=True, max_length=200, null=True)),
                ('orca_refe', models.CharField(blank=True, max_length=50, null=True)),
                ('orca_data_repr', models.DateField(blank=True, null=True)),
                ('orca_data_apro', models.DateField(blank=True, null=True)),
                ('orca_bloq', models.DateField(blank=True, null=True)),
                ('orca_tipo_gara', models.BooleanField(blank=True, null=True)),
                ('orca_tipo_cort', models.BooleanField(blank=True, null=True)),
                ('orca_tipo_seco', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orcamento',
                'unique_together': {('orca_empr', 'orca_fili', 'orca_codi')},
            },
        ),
        migrations.CreateModel(
            name='OrcamentoPecas',
            fields=[
                ('peca_id', models.AutoField(primary_key=True, serialize=False)),
                ('peca_empr', models.IntegerField()),
                ('peca_fili', models.IntegerField()),
                ('peca_codi', models.CharField(max_length=50)),
                ('peca_quan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peca_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peca_tota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('peca_comp', models.TextField(blank=True, null=True)),
                ('peca_orca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='orcamentos.orcamento')),
            ],
            options={
                'db_table': 'orcamentopecas',
            },
        ),
    ]
