# Generated by Django 2.2.28 on 2025-11-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('pedi_empr', models.IntegerField()),
                ('pedi_fili', models.IntegerField()),
                ('pedi_nume', models.IntegerField(db_column='pedi_nume', primary_key=True, serialize=False, unique=True)),
                ('pedi_forn', models.CharField(db_column='pedi_forn', max_length=60)),
                ('pedi_data', models.DateField()),
                ('pedi_topr', models.DecimalField(blank=True, db_column='pedi_topr', decimal_places=2, max_digits=15, null=True)),
                ('pedi_tota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pedi_vend', models.CharField(blank=True, db_column='pedi_vend', max_length=15, null=True)),
                ('pedi_obse', models.TextField(blank=True, null=True)),
                ('pedi_nume_pedi', models.IntegerField(blank=True, db_column='pedi_nume_pedi', null=True)),
                ('pedi_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'orcamentosvenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('iped_empr', models.IntegerField(db_column='iped_empr')),
                ('iped_fili', models.IntegerField()),
                ('iped_pedi', models.ForeignKey(db_column='iped_pedi', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='itens', serialize=False, to='orcamentos.Orcamentos')),
                ('iped_item', models.IntegerField()),
                ('iped_prod', models.CharField(db_column='iped_prod', max_length=60)),
                ('iped_quan', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('iped_suto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iped_unit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('iped_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iped_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iped_unli', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('iped_forn', models.IntegerField(blank=True, null=True)),
                ('iped_pdes_item', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iped_data', models.DateField()),
            ],
            options={
                'db_table': 'itensorcamentovenda',
                'managed': False,
            },
        ),
    ]
