# Generated by Django 5.1.5 on 2025-02-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0002_alter_entidades_enti_fant_alter_entidades_enti_nome'),
        ('orcamentos', '0001_initial'),
        ('produto', '0003_rename_produto_saldoproduto_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='orca_enti',
            field=models.ForeignKey(blank=True, db_column='orca_enti', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_por_clientes', to='Entidades.entidades'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='orca_vend',
            field=models.ForeignKey(blank=True, db_column='orca_vend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_como_vendedor', to='Entidades.entidades'),
        ),
        migrations.AlterField(
            model_name='orcamentopecas',
            name='peca_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.produtos'),
        ),
    ]
