# Generated by Django 5.1.1 on 2025-02-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orcamento',
            table='orcamentosvenda',
        ),
    ]
