# Generated by Django 5.1.1 on 2025-02-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_orca_enti_alter_orcamento_orca_vend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='orca_aber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
