# Generated by Django 5.1.1 on 2025-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='orca_id',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='orca_tipo_cort',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='orca_tipo_gara',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='orca_tipo_seco',
        ),
        migrations.RemoveField(
            model_name='orcamentopecas',
            name='peca_comp',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='orca_aber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='orca_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='orca_stat',
            field=models.CharField(blank=True, choices=[('1', 'Aberto'), ('2', 'Em Andamento'), ('3', 'Fechado'), ('4', 'Cancelado')], max_length=1, null=True),
        ),
    ]
