# Generated by Django 5.1.1 on 2025-02-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0001_initial'),
        ('orcamentos', '0003_remove_orcamento_orca_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_aber',
            new_name='pedi_aber',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_bloq',
            new_name='pedi_bloq',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_codi',
            new_name='pedi_codi',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_cond',
            new_name='pedi_cond',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_data_alte',
            new_name='pedi_data_alte',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_data_apro',
            new_name='pedi_data_apro',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_data_repr',
            new_name='pedi_data_repr',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_empr',
            new_name='pedi_empr',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_fili',
            new_name='pedi_fili',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_gara',
            new_name='pedi_gara',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_obse',
            new_name='pedi_obse',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_orde_refe',
            new_name='pedi_orde_refe',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_praz_entr',
            new_name='pedi_praz_entr',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_refe',
            new_name='pedi_refe',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_resp',
            new_name='pedi_resp',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_soli',
            new_name='pedi_soli',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_stat',
            new_name='pedi_stat',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_tipo_fret',
            new_name='pedi_tipo_fret',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_tipo_impo',
            new_name='pedi_tipo_impo',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_vali',
            new_name='pedi_vali',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_valo_desc',
            new_name='pedi_valo_desc',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_valo_fret',
            new_name='pedi_valo_fret',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_valo_outr',
            new_name='pedi_valo_outr',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='orca_valo_tota',
            new_name='pedi_valo_tota',
        ),
        migrations.RenameField(
            model_name='orcamentopecas',
            old_name='peca_orca',
            new_name='peca_pedi',
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('pedi_empr', 'pedi_fili', 'pedi_codi')},
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_enti',
            field=models.ForeignKey(blank=True, db_column='pedi_enti', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_por_clientes', to='Entidades.entidades'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_vend',
            field=models.ForeignKey(blank=True, db_column='pedi_vend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_como_vendedor', to='Entidades.entidades'),
        ),
        migrations.AlterModelTable(
            name='orcamentopecas',
            table='orcamentotopecas',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='orca_enti',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='orca_vend',
        ),
    ]
