# Generated by Django 5.1.1 on 2025-02-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_rename_orca_aber_orcamento_pedi_aber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_aber',
            new_name='pedi_data',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_codi',
            new_name='pedi_nume',
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('pedi_empr', 'pedi_fili', 'pedi_nume')},
        ),
    ]
