# Generated by Django 5.1.1 on 2025-02-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_rename_pedi_aber_orcamento_pedi_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_enti',
            new_name='pedi_clie',
        ),
    ]
