# Generated by Django 5.1.1 on 2025-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_rename_pedi_enti_orcamento_pedi_clie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_clie',
            new_name='pedi_forn',
        ),
    ]
