# Generated by Django 5.1.1 on 2025-02-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0001_initial'),
        ('orcamentos', '0007_rename_pedi_clie_orcamento_pedi_forn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='pedi_forn',
            field=models.ForeignKey(blank=True, db_column='pedi_forn', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_por_clientes', to='Entidades.entidades'),
        ),
    ]
