# Generated by Django 5.1.1 on 2025-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_alter_orcamento_pedi_forn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_cond',
            new_name='pedi_cond_rece',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_bloq',
            new_name='pedi_data_libe',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_valo_desc',
            new_name='pedi_desc',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_valo_outr',
            new_name='pedi_tota',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='pedi_orde_refe',
            new_name='pedi_usua_libe',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_data_alte',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_data_apro',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_data_repr',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_gara',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_praz_entr',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_refe',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_resp',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_soli',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_tipo_fret',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_tipo_impo',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedi_valo_tota',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_fret_por',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_hora_libe',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_libe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_nao_libe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_obse_nao_libe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_plac',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedi_veic',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
