# Generated by Django 5.1.1 on 2025-02-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0010_orcamentosvenda_rename_pedi_stat_orcamento_pedi_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orcamentopecas',
            table='orcamentopecas',
        ),
    ]
