# Generated by Django 5.1.1 on 2025-02-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0011_alter_orcamentopecas_table'),
        ('produto', '0002_alter_saldoproduto_sapr_empr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentopecas',
            name='peca_codi',
            field=models.ForeignKey(db_column='peca_codi', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.produtos'),
        ),
        migrations.AlterField(
            model_name='orcamentopecas',
            name='peca_pedi',
            field=models.ForeignKey(db_column='peca_pedi', on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='orcamentos.orcamento'),
        ),
    ]
