# Generated by Django 5.1.1 on 2025-02-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0012_alter_orcamentopecas_peca_codi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentopecas',
            name='peca_pedi',
        ),
        migrations.AddField(
            model_name='orcamentopecas',
            name='peca_comp',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orcamentopecas',
            name='peca_orca',
            field=models.ForeignKey(db_column='peca_orca', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='orcamentos.orcamento'),
            preserve_default=False,
        ),
    ]
