# Generated by Django 2.2.28 on 2025-11-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Número de identificação ou tag do animal', max_length=100, unique=True)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True)),
                ('peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animais',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_aplicada', models.DecimalField(decimal_places=2, help_text='Quantidade de insumo aplicada', max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aplicacao_insumos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categorias_produtos',
            },
        ),
        migrations.CreateModel(
            name='CicloFlorestal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(help_text='Tipo de cultura florestal (ex: Eucalipto, Pinus)', max_length=255)),
                ('data_plantio', models.DateField()),
                ('data_previsao_colheita', models.DateField(blank=True, null=True)),
                ('data_colheita', models.DateField(blank=True, null=True)),
                ('volume_esperado', models.DecimalField(blank=True, decimal_places=2, help_text='Volume esperado da colheita (em m³ ou outra unidade)', max_digits=10, null=True)),
                ('volume_real', models.DecimalField(blank=True, decimal_places=2, help_text='Volume efetivamente colhido', max_digits=10, null=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, help_text='Custo total do ciclo (produção, insumos, mão de obra, etc.)', max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ciclos_florestais',
            },
        ),
        migrations.CreateModel(
            name='EstoqueFazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_medio_atualizado', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio atualizado com base nas movimentações', max_digits=10)),
            ],
            options={
                'db_table': 'estoque_fazenda',
            },
        ),
        migrations.CreateModel(
            name='EventoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('nascimento', 'Nascimento'), ('vacinacao', 'Vacinação'), ('engorda', 'Engorda'), ('abate', 'Abate'), ('venda', 'Venda')], max_length=50)),
                ('data_evento', models.DateField()),
                ('custo', models.DecimalField(blank=True, decimal_places=2, help_text='Custo associado a esse evento (se aplicável)', max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos_animais',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fazendas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_movimentacoes',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Custo unitário na movimentação (para atualização do custo médio)', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'movimentacao_estoque',
            },
        ),
        migrations.CreateModel(
            name='ProdutoAgro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio do produto', max_digits=10)),
            ],
            options={
                'db_table': 'produtos_agro',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área do talhão (pode ser em hectares ou m²)', max_digits=10)),
                ('unidade_medida', models.CharField(default='hectares', help_text='Unidade de medida da área (ex: hectares, m²)', max_length=20)),
            ],
            options={
                'db_table': 'talhoes',
            },
        ),
    ]
