# Generated by Django 2.2.28 on 2025-11-04 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agricola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='talhao',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='Agricola.Fazenda'),
        ),
        migrations.AddField(
            model_name='talhao',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='produtoagro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agricola.CategoriaProduto'),
        ),
        migrations.AddField(
            model_name='produtoagro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='produtoagro',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='Agricola.Fazenda'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agricola.ProdutoAgro'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agricola.Fazenda'),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Agricola.MovimentacaoEstoque'),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agricola.ProdutoAgro'),
        ),
        migrations.AddField(
            model_name='historicomovimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='empr_faze',
            field=models.ForeignKey(db_column='empr_faze', on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='fili_faze',
            field=models.ForeignKey(db_column='empr_fili', on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='eventoanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Agricola.Animal'),
        ),
        migrations.AddField(
            model_name='eventoanimal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='eventoanimal',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='eventoanimal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estoquefazenda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='estoquefazenda',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Agricola.Fazenda'),
        ),
        migrations.AddField(
            model_name='estoquefazenda',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='estoquefazenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agricola.ProdutoAgro'),
        ),
        migrations.AddField(
            model_name='cicloflorestal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='cicloflorestal',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='cicloflorestal',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_florestais', to='Agricola.Talhao'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='aplicacaoinsumos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='aplicacaoinsumos',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AddField(
            model_name='aplicacaoinsumos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agricola.ProdutoAgro'),
        ),
        migrations.AddField(
            model_name='aplicacaoinsumos',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacaoinsumos',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_insumos', to='Agricola.Talhao'),
        ),
        migrations.AddField(
            model_name='animal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Empresas'),
        ),
        migrations.AddField(
            model_name='animal',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='Agricola.Fazenda'),
        ),
        migrations.AddField(
            model_name='animal',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencas.Filiais'),
        ),
        migrations.AlterUniqueTogether(
            name='estoquefazenda',
            unique_together={('fazenda', 'produto')},
        ),
    ]
