# Generated by Django 5.1.1 on 2025-02-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0002_historicomovimentacao'),
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licencas.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fazenda',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='licencas.filiais'),
            preserve_default=False,
        ),
    ]
