# Generated by Django 5.1.1 on 2025-02-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0003_fazenda_empresa_fazenda_filial'),
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='filial',
        ),
        migrations.AddField(
            model_name='fazenda',
            name='empr_faze',
            field=models.ForeignKey(db_column='empr_faze', default=1, on_delete=django.db.models.deletion.CASCADE, to='licencas.empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fazenda',
            name='fili_faze',
            field=models.ForeignKey(db_column='empr_fili', default=1, on_delete=django.db.models.deletion.CASCADE, to='licencas.filiais'),
            preserve_default=False,
        ),
    ]
